version: '3.8'
services:
  worker-gpt4:
    build: ./worker-gpt4
    environment:
      REDIS_ADDR: label-platform-redis:6379
      REDIS_PASSWORD: ""
      OPENAI_API_KEY: 
    networks:
      - label-platform-network

  worker-claude:
    build: ./worker-claude
    environment:
      REDIS_ADDR: label-platform-redis:6379
      REDIS_PASSWORD: ""
      CLAUDE_API_KEY: 
    networks:
      - label-platform-network

  worker-gemini:
    build: ./worker-gemini
    environment:
      REDIS_ADDR: label-platform-redis:6379
      REDIS_PASSWORD: ""
      GEMINI_API_KEY: 
    networks:
      - label-platform-network

  result-consumer:
    build: ./worker-result-consumer
    environment:
      REDIS_ADDR: label-platform-redis:6379
      REDIS_PASSWORD: ""
      POSTGRES_DSN: "host=label-platform-postgres user=postgres password=password dbname=label_platform port=5432 sslmode=disable"
      BACKEND_NOTIFY_URL: "http://host.docker.internal:8080/api/v1/predict/notify"
    networks:
      - label-platform-network

networks:
  label-platform-network:
    external: true